version: '3.8'

services:
  mock-services:
    image: pactfoundation/pact-stub-server:latest
    container_name: mock-services
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./pacts:/app/pacts:ro
    environment:
      - PACT_BROKER_BASE_URL=http://localhost:8080
    command: >
      --port 8080
      --dir /app/pacts
      --cors
    networks:
      - test-network

  kubernetes-api-mock:
    image: nginx:alpine
    container_name: k8s-api-mock
    ports:
      - "8443:80"
    volumes:
      - ./mocks/k8s-api:/usr/share/nginx/html:ro
      - ./mocks/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - test-network

  network-service-mock:
    image: nginx:alpine
    container_name: network-mock
    ports:
      - "9090:80"
    volumes:
      - ./mocks/network-api:/usr/share/nginx/html:ro
      - ./mocks/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - test-network

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: contract-test-runner
    volumes:
      - ../:/app:ro
      - ./test-results:/app/test-results
    environment:
      - PACT_BROKER_BASE_URL=http://mock-services:8080
      - K8S_API_URL=http://kubernetes-api-mock:80
      - NETWORK_API_URL=http://network-service-mock:80
    depends_on:
      - mock-services
      - kubernetes-api-mock
      - network-service-mock
    networks:
      - test-network
    profiles:
      - test

networks:
  test-network:
    driver: bridge 