global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # agregar reglas de alertas aqui si es necesario

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kubernetes-master'
    static_configs:
      - targets: ['k8s-master:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'kubernetes-workers'
    static_configs:
      - targets: ['k8s-worker-1:80', 'k8s-worker-2:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'nginx-demo'
    static_configs:
      - targets: ['nginx-demo:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 60s 